// These constants is to fetch featured products data
export const FEATURED_PRODUCT_LIST_REQUEST = 'FEATURED_PRODUCT_LIST_REQUEST';
export const FEATURED_PRODUCT_LIST_SUCCESS = 'FEATURED_PRODUCT_LIST_SUCCESS';
export const FEATURED_PRODUCT_LIST_FAIL = 'FEATURED_PRODUCT_LIST_FAIL';

// These constants is to fetch the recent products data
export const RECENT_PRODUCT_LIST_REQUEST = 'RECENT_PRODUCT_LIST_REQUEST';
export const RECENT_PRODUCT_LIST_SUCCESS = 'RECENT_PRODUCT_LIST_SUCCESS'
export const RECENT_PRODUCT_LIST_FAIL = 'RECENT_PRODUCT_LIST_FAIL';